### PR TITLE
Unsafe proto release cleanup

### PR DESCRIPTION
**Pull request by mkruskal-google**
MUST_USE_RESULT is being added to these release methods, which will break this code as it's currently written.  This change is part of an internal google effort to fix these instances before enabling PROTOBUF_MUST_USE_RESULT.

The unsafe arena variants of set_allocated_* and release_* will not require the result to be checked, and will also avoid unwanted copies or memory leaks if the protos are owned by an arena.

### CODE REVIEW

**Review by antoninbas — COMMENTED** [review]
Thanks for the patch. Is there any public resource that you can link to about that upcoming Protobuf change?
I believe some tests under https://github.com/p4lang/PI/tree/main/proto/tests also use these functions.

**Comment by fowles** [comment]
The current usage is actually out of contract for protos that are on arenas.  The internal changes to google are to make broader use of arenas internally.

**Comment by mkruskal-google** [comment]
Ah, thanks for the pointer!  I don't think we build the tests internally so I didn't pick them up.

See Matt's comment about the changes.  This shouldn't really have any affect on you, being outside google, but this does clean up a misuse that could cause issues for you in the future

**Review by antoninbas — APPROVED** [review]
LGTM

**Comment by antoninbas** [comment]
@mkruskal-google CI is failing because of cpplint failures
```
PI/tools/../proto/tests/test_proto_fe.cpp:2685:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
PI/tools/../proto/tests/test_proto_fe.cpp:2697:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
```

**Comment by mkruskal-google** [comment]
Thanks Antonin, fixed!

**Comment by antoninbas** [comment]
I see some build failures:

```
src/device_mgr.cpp:605:17: error: no member named 'unsafe_arena_set_allocated_entity' in 'p4::v1::Update'
        update->unsafe_arena_set_allocated_entity(&entity);
        ~~~~~~  ^
src/device_mgr.cpp:609:16: error: no member named 'unsafe_arena_release_entity' in 'p4::v1::Update'
        update.unsafe_arena_release_entity();
        ~~~~~~ ^
src/device_mgr.cpp:1601:9: error: no member named 'unsafe_arena_set_allocated_error' in 'p4::v1::StreamMessageResponse'
    msg.unsafe_arena_set_allocated_error(&stream_error);
    ~~~ ^
src/device_mgr.cpp:1603:9: error: no member named 'unsafe_arena_release_error' in 'p4::v1::StreamMessageResponse'
    msg.unsafe_arena_release_error();
    ~~~ ^
```

The CI uses Protobuf / protoc 3.6. Is it possible that these new methods were introduced in a more recent version?

**Comment by mkruskal-google** [comment]
Yep, I'm looking into that now, but I came to the same conclusion.  I see two options:
1) Bump up the version of protobuf used for CI
2) Find a workaround (e.g. "option cc_enable_arenas = true" should enable it in some past versions, although I'm not sure about the one you're using)

I'm looking into 2, but WDYT of 1?

**Comment by antoninbas** [comment]
I would personally be ok with updating the Protobuf version used for CI, but it may impact other people so it may be a bit tedious to do. We use a single version for all p4.org projects, and some downstream projects user this version as well. It comes from https://github.com/p4lang/third-party.

I guess one solution would be to use one method or the other based on the value of the `GOOGLE_PROTOBUF_VERSION` preprocessor macro.
It's not perfect because there can be a discrepancy between the protoc version and the version of the protobuf headers. However, there is the following guarantee: `protoc version <= protobuf version`, so I think it will work for your scenario and for CI as well. Only issue would be if someone has a version mismatch, with 1) a version of protoc that doesn't generate the new methods and 2) a version of Protobuf that matches to a version of protoc that does generate them. Personally I can live with that.

Have you considered just fixing the usage of `set_allocated_*` and `release_*` in the PI code?

**Comment by mkruskal-google** [comment]
https://github.com/p4lang/p4runtime/pull/348 *should* fix this issue without bumping up the version.

I did consider removing the usage.  The problem is this is a perfectly valid use case.  You're adding an externally owned pointer to the proto, serializing it, and then removing it again to avoid freeing it.  This is the best way to avoid a copy.

**Comment by mkruskal-google** [comment]
Do I need to do anything to pull in the changes to p4runtime and rerun the tests?

**Comment by antoninbas** [comment]
Yes you need to update the Git submodule pointer in that folder: https://github.com/p4lang/PI/tree/main/proto
And update the P4Runtime commit for the Bazel build: https://github.com/p4lang/PI/blob/main/bazel/deps.bzl

**Comment by mkruskal-google** [comment]
Thanks Antonin!  I *think* that should cover it?  I'm a little nervous about that comment in deps.bzl

**Review by antoninbas — APPROVED** [review]

**Pull request merged**
