### PR TITLE
Make PI compilable in google3

### PR DESCRIPTION
**Pull request by chenxinming05**
This CL changes a place in proto/frontend/src/device_mgr.cpp to
 eliminate the "unused variable" error.

### CODE REVIEW

**Comment by sethfowler** [comment]
google3 is not compiling in C99 mode?

**Comment by chenxinming05** [comment]
Not for pure c files. I can use an option -std=c99, but that breaks the strdup function.

third_party/p4lang_PI/src/p4info/actions.c:157:18: error: implicit declaration of function 'strdup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  action->name = strdup(name);

So either we fix the for loop, or we fix the strdup function.

**Comment by sethfowler** [comment]
It'd be much better to replace the call to `strdup` with code that uses `strncpy` or something similar. (Or figure out what #define is required to make `strdup` available with your compiler.)

**Comment by antoninbas** [comment]
I am with @sethfowler on this. It would be much better to figure out how you can make strdup available. If this is a major roadblock, you can provide a strdup implementation under lib in this repo and use it instead; I believe that would be a better pull request. Declaring the loop iteration variable outside of the loop like this makes the code less clear.

**Comment by ChrisDodd** [comment]
strdup should be defined in <string.h> according to POSIX (which has defined it pretty much from the start -- 1986?)

**Comment by chenxinming05** [comment]
I did the trick by adding "-std=c11 -D_GNU_SOURCE" as the compiler parameter, so I'll discard the for loop changes.

strdup is not ANSI C so it's not visible in C99 and up by default.

**Comment by chenxinming05** [comment]
Please take another look. I've updated the changes.

**Comment by antoninbas** [comment]
I think that by default the compilers we use (locally or in regressions) all use `gnu11` as default, which is why we don't face the issue. The Google compiler probably conforms to ANSI C by default. I will open an issue for myself to document this requirement in the README.

**Pull request merged**
